// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: shared/proto/institute/institute.proto

package institute

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Institute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Institute) Reset() {
	*x = Institute{}
	mi := &file_shared_proto_institute_institute_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Institute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Institute) ProtoMessage() {}

func (x *Institute) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_institute_institute_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Institute.ProtoReflect.Descriptor instead.
func (*Institute) Descriptor() ([]byte, []int) {
	return file_shared_proto_institute_institute_proto_rawDescGZIP(), []int{0}
}

func (x *Institute) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Institute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Institute) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Institute) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateInstituteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInstituteRequest) Reset() {
	*x = CreateInstituteRequest{}
	mi := &file_shared_proto_institute_institute_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstituteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstituteRequest) ProtoMessage() {}

func (x *CreateInstituteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_institute_institute_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstituteRequest.ProtoReflect.Descriptor instead.
func (*CreateInstituteRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_institute_institute_proto_rawDescGZIP(), []int{1}
}

func (x *CreateInstituteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateInstituteRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type CreateInstituteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Institute     *Institute             `protobuf:"bytes,1,opt,name=institute,proto3" json:"institute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInstituteResponse) Reset() {
	*x = CreateInstituteResponse{}
	mi := &file_shared_proto_institute_institute_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstituteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstituteResponse) ProtoMessage() {}

func (x *CreateInstituteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_institute_institute_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstituteResponse.ProtoReflect.Descriptor instead.
func (*CreateInstituteResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_institute_institute_proto_rawDescGZIP(), []int{2}
}

func (x *CreateInstituteResponse) GetInstitute() *Institute {
	if x != nil {
		return x.Institute
	}
	return nil
}

type AddInstituteAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstituteId   string                 `protobuf:"bytes,1,opt,name=institute_id,json=instituteId,proto3" json:"institute_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddInstituteAdminRequest) Reset() {
	*x = AddInstituteAdminRequest{}
	mi := &file_shared_proto_institute_institute_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddInstituteAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddInstituteAdminRequest) ProtoMessage() {}

func (x *AddInstituteAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_institute_institute_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddInstituteAdminRequest.ProtoReflect.Descriptor instead.
func (*AddInstituteAdminRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_institute_institute_proto_rawDescGZIP(), []int{3}
}

func (x *AddInstituteAdminRequest) GetInstituteId() string {
	if x != nil {
		return x.InstituteId
	}
	return ""
}

func (x *AddInstituteAdminRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AddInstituteAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddInstituteAdminResponse) Reset() {
	*x = AddInstituteAdminResponse{}
	mi := &file_shared_proto_institute_institute_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddInstituteAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddInstituteAdminResponse) ProtoMessage() {}

func (x *AddInstituteAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_institute_institute_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddInstituteAdminResponse.ProtoReflect.Descriptor instead.
func (*AddInstituteAdminResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_institute_institute_proto_rawDescGZIP(), []int{4}
}

func (x *AddInstituteAdminResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetInstituteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstituteRequest) Reset() {
	*x = GetInstituteRequest{}
	mi := &file_shared_proto_institute_institute_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstituteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstituteRequest) ProtoMessage() {}

func (x *GetInstituteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_institute_institute_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstituteRequest.ProtoReflect.Descriptor instead.
func (*GetInstituteRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_institute_institute_proto_rawDescGZIP(), []int{5}
}

func (x *GetInstituteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetInstituteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Institute     *Institute             `protobuf:"bytes,1,opt,name=institute,proto3" json:"institute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstituteResponse) Reset() {
	*x = GetInstituteResponse{}
	mi := &file_shared_proto_institute_institute_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstituteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstituteResponse) ProtoMessage() {}

func (x *GetInstituteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_institute_institute_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstituteResponse.ProtoReflect.Descriptor instead.
func (*GetInstituteResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_institute_institute_proto_rawDescGZIP(), []int{6}
}

func (x *GetInstituteResponse) GetInstitute() *Institute {
	if x != nil {
		return x.Institute
	}
	return nil
}

var File_shared_proto_institute_institute_proto protoreflect.FileDescriptor

const file_shared_proto_institute_institute_proto_rawDesc = "" +
	"\n" +
	"&shared/proto/institute/institute.proto\x12\tinstitute\"b\n" +
	"\tInstitute\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"@\n" +
	"\x16CreateInstituteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"M\n" +
	"\x17CreateInstituteResponse\x122\n" +
	"\tinstitute\x18\x01 \x01(\v2\x14.institute.InstituteR\tinstitute\"V\n" +
	"\x18AddInstituteAdminRequest\x12!\n" +
	"\finstitute_id\x18\x01 \x01(\tR\vinstituteId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"5\n" +
	"\x19AddInstituteAdminResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"%\n" +
	"\x13GetInstituteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x14GetInstituteResponse\x122\n" +
	"\tinstitute\x18\x01 \x01(\v2\x14.institute.InstituteR\tinstitute2\x9d\x02\n" +
	"\x10InstituteService\x12X\n" +
	"\x0fCreateInstitute\x12!.institute.CreateInstituteRequest\x1a\".institute.CreateInstituteResponse\x12^\n" +
	"\x11AddInstituteAdmin\x12#.institute.AddInstituteAdminRequest\x1a$.institute.AddInstituteAdminResponse\x12O\n" +
	"\fGetInstitute\x12\x1e.institute.GetInstituteRequest\x1a\x1f.institute.GetInstituteResponseB>Z<github.com/gradeloop/core/services/go/shared/proto/instituteb\x06proto3"

var (
	file_shared_proto_institute_institute_proto_rawDescOnce sync.Once
	file_shared_proto_institute_institute_proto_rawDescData []byte
)

func file_shared_proto_institute_institute_proto_rawDescGZIP() []byte {
	file_shared_proto_institute_institute_proto_rawDescOnce.Do(func() {
		file_shared_proto_institute_institute_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_institute_institute_proto_rawDesc), len(file_shared_proto_institute_institute_proto_rawDesc)))
	})
	return file_shared_proto_institute_institute_proto_rawDescData
}

var file_shared_proto_institute_institute_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_shared_proto_institute_institute_proto_goTypes = []any{
	(*Institute)(nil),                 // 0: institute.Institute
	(*CreateInstituteRequest)(nil),    // 1: institute.CreateInstituteRequest
	(*CreateInstituteResponse)(nil),   // 2: institute.CreateInstituteResponse
	(*AddInstituteAdminRequest)(nil),  // 3: institute.AddInstituteAdminRequest
	(*AddInstituteAdminResponse)(nil), // 4: institute.AddInstituteAdminResponse
	(*GetInstituteRequest)(nil),       // 5: institute.GetInstituteRequest
	(*GetInstituteResponse)(nil),      // 6: institute.GetInstituteResponse
}
var file_shared_proto_institute_institute_proto_depIdxs = []int32{
	0, // 0: institute.CreateInstituteResponse.institute:type_name -> institute.Institute
	0, // 1: institute.GetInstituteResponse.institute:type_name -> institute.Institute
	1, // 2: institute.InstituteService.CreateInstitute:input_type -> institute.CreateInstituteRequest
	3, // 3: institute.InstituteService.AddInstituteAdmin:input_type -> institute.AddInstituteAdminRequest
	5, // 4: institute.InstituteService.GetInstitute:input_type -> institute.GetInstituteRequest
	2, // 5: institute.InstituteService.CreateInstitute:output_type -> institute.CreateInstituteResponse
	4, // 6: institute.InstituteService.AddInstituteAdmin:output_type -> institute.AddInstituteAdminResponse
	6, // 7: institute.InstituteService.GetInstitute:output_type -> institute.GetInstituteResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shared_proto_institute_institute_proto_init() }
func file_shared_proto_institute_institute_proto_init() {
	if File_shared_proto_institute_institute_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_institute_institute_proto_rawDesc), len(file_shared_proto_institute_institute_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_institute_institute_proto_goTypes,
		DependencyIndexes: file_shared_proto_institute_institute_proto_depIdxs,
		MessageInfos:      file_shared_proto_institute_institute_proto_msgTypes,
	}.Build()
	File_shared_proto_institute_institute_proto = out.File
	file_shared_proto_institute_institute_proto_goTypes = nil
	file_shared_proto_institute_institute_proto_depIdxs = nil
}
