// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: shared/proto/institute/institute.proto

package institute

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InstituteService_CreateInstitute_FullMethodName   = "/institute.InstituteService/CreateInstitute"
	InstituteService_AddInstituteAdmin_FullMethodName = "/institute.InstituteService/AddInstituteAdmin"
	InstituteService_GetInstitute_FullMethodName      = "/institute.InstituteService/GetInstitute"
)

// InstituteServiceClient is the client API for InstituteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InstituteServiceClient interface {
	CreateInstitute(ctx context.Context, in *CreateInstituteRequest, opts ...grpc.CallOption) (*CreateInstituteResponse, error)
	AddInstituteAdmin(ctx context.Context, in *AddInstituteAdminRequest, opts ...grpc.CallOption) (*AddInstituteAdminResponse, error)
	GetInstitute(ctx context.Context, in *GetInstituteRequest, opts ...grpc.CallOption) (*GetInstituteResponse, error)
}

type instituteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInstituteServiceClient(cc grpc.ClientConnInterface) InstituteServiceClient {
	return &instituteServiceClient{cc}
}

func (c *instituteServiceClient) CreateInstitute(ctx context.Context, in *CreateInstituteRequest, opts ...grpc.CallOption) (*CreateInstituteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInstituteResponse)
	err := c.cc.Invoke(ctx, InstituteService_CreateInstitute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instituteServiceClient) AddInstituteAdmin(ctx context.Context, in *AddInstituteAdminRequest, opts ...grpc.CallOption) (*AddInstituteAdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddInstituteAdminResponse)
	err := c.cc.Invoke(ctx, InstituteService_AddInstituteAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instituteServiceClient) GetInstitute(ctx context.Context, in *GetInstituteRequest, opts ...grpc.CallOption) (*GetInstituteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInstituteResponse)
	err := c.cc.Invoke(ctx, InstituteService_GetInstitute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InstituteServiceServer is the server API for InstituteService service.
// All implementations must embed UnimplementedInstituteServiceServer
// for forward compatibility.
type InstituteServiceServer interface {
	CreateInstitute(context.Context, *CreateInstituteRequest) (*CreateInstituteResponse, error)
	AddInstituteAdmin(context.Context, *AddInstituteAdminRequest) (*AddInstituteAdminResponse, error)
	GetInstitute(context.Context, *GetInstituteRequest) (*GetInstituteResponse, error)
	mustEmbedUnimplementedInstituteServiceServer()
}

// UnimplementedInstituteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInstituteServiceServer struct{}

func (UnimplementedInstituteServiceServer) CreateInstitute(context.Context, *CreateInstituteRequest) (*CreateInstituteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInstitute not implemented")
}
func (UnimplementedInstituteServiceServer) AddInstituteAdmin(context.Context, *AddInstituteAdminRequest) (*AddInstituteAdminResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddInstituteAdmin not implemented")
}
func (UnimplementedInstituteServiceServer) GetInstitute(context.Context, *GetInstituteRequest) (*GetInstituteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstitute not implemented")
}
func (UnimplementedInstituteServiceServer) mustEmbedUnimplementedInstituteServiceServer() {}
func (UnimplementedInstituteServiceServer) testEmbeddedByValue()                          {}

// UnsafeInstituteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InstituteServiceServer will
// result in compilation errors.
type UnsafeInstituteServiceServer interface {
	mustEmbedUnimplementedInstituteServiceServer()
}

func RegisterInstituteServiceServer(s grpc.ServiceRegistrar, srv InstituteServiceServer) {
	// If the following call panics, it indicates UnimplementedInstituteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InstituteService_ServiceDesc, srv)
}

func _InstituteService_CreateInstitute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInstituteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstituteServiceServer).CreateInstitute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstituteService_CreateInstitute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstituteServiceServer).CreateInstitute(ctx, req.(*CreateInstituteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstituteService_AddInstituteAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddInstituteAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstituteServiceServer).AddInstituteAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstituteService_AddInstituteAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstituteServiceServer).AddInstituteAdmin(ctx, req.(*AddInstituteAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstituteService_GetInstitute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstituteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstituteServiceServer).GetInstitute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstituteService_GetInstitute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstituteServiceServer).GetInstitute(ctx, req.(*GetInstituteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InstituteService_ServiceDesc is the grpc.ServiceDesc for InstituteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InstituteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "institute.InstituteService",
	HandlerType: (*InstituteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateInstitute",
			Handler:    _InstituteService_CreateInstitute_Handler,
		},
		{
			MethodName: "AddInstituteAdmin",
			Handler:    _InstituteService_AddInstituteAdmin_Handler,
		},
		{
			MethodName: "GetInstitute",
			Handler:    _InstituteService_GetInstitute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shared/proto/institute/institute.proto",
}
