// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: libs/proto/user/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	InstituteId   string                 `protobuf:"bytes,5,opt,name=institute_id,json=instituteId,proto3" json:"institute_id,omitempty"`
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,7,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_libs_proto_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_libs_proto_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserProfile) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserProfile) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProfile) GetInstituteId() string {
	if x != nil {
		return x.InstituteId
	}
	return ""
}

func (x *UserProfile) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserProfile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_libs_proto_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_libs_proto_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_libs_proto_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_libs_proto_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProfileRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateProfileRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateProfileRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type Institute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Domain        string                 `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Institute) Reset() {
	*x = Institute{}
	mi := &file_libs_proto_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Institute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Institute) ProtoMessage() {}

func (x *Institute) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Institute.ProtoReflect.Descriptor instead.
func (*Institute) Descriptor() ([]byte, []int) {
	return file_libs_proto_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *Institute) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Institute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Institute) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Institute) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type CreateInstituteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	AdminEmail    string                 `protobuf:"bytes,4,opt,name=admin_email,json=adminEmail,proto3" json:"admin_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInstituteRequest) Reset() {
	*x = CreateInstituteRequest{}
	mi := &file_libs_proto_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstituteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstituteRequest) ProtoMessage() {}

func (x *CreateInstituteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstituteRequest.ProtoReflect.Descriptor instead.
func (*CreateInstituteRequest) Descriptor() ([]byte, []int) {
	return file_libs_proto_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *CreateInstituteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateInstituteRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateInstituteRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CreateInstituteRequest) GetAdminEmail() string {
	if x != nil {
		return x.AdminEmail
	}
	return ""
}

type CreateUserRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Email       string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	FirstName   string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName    string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	InstituteId string                 `protobuf:"bytes,4,opt,name=institute_id,json=instituteId,proto3" json:"institute_id,omitempty"`
	// Specific fields
	EnrollmentNumber string `protobuf:"bytes,5,opt,name=enrollment_number,json=enrollmentNumber,proto3" json:"enrollment_number,omitempty"` // For students
	Specialization   string `protobuf:"bytes,6,opt,name=specialization,proto3" json:"specialization,omitempty"`                             // For instructors
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_libs_proto_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_libs_proto_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateUserRequest) GetInstituteId() string {
	if x != nil {
		return x.InstituteId
	}
	return ""
}

func (x *CreateUserRequest) GetEnrollmentNumber() string {
	if x != nil {
		return x.EnrollmentNumber
	}
	return ""
}

func (x *CreateUserRequest) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	TempPassword  string                 `protobuf:"bytes,3,opt,name=temp_password,json=tempPassword,proto3" json:"temp_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_libs_proto_user_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_user_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_libs_proto_user_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResponse) GetTempPassword() string {
	if x != nil {
		return x.TempPassword
	}
	return ""
}

type BulkImportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstituteId   string                 `protobuf:"bytes,1,opt,name=institute_id,json=instituteId,proto3" json:"institute_id,omitempty"`
	CsvData       []byte                 `protobuf:"bytes,2,opt,name=csv_data,json=csvData,proto3" json:"csv_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkImportRequest) Reset() {
	*x = BulkImportRequest{}
	mi := &file_libs_proto_user_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkImportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkImportRequest) ProtoMessage() {}

func (x *BulkImportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_user_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkImportRequest.ProtoReflect.Descriptor instead.
func (*BulkImportRequest) Descriptor() ([]byte, []int) {
	return file_libs_proto_user_user_proto_rawDescGZIP(), []int{7}
}

func (x *BulkImportRequest) GetInstituteId() string {
	if x != nil {
		return x.InstituteId
	}
	return ""
}

func (x *BulkImportRequest) GetCsvData() []byte {
	if x != nil {
		return x.CsvData
	}
	return nil
}

type BulkImportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount  int32                  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailureCount  int32                  `protobuf:"varint,2,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkImportResponse) Reset() {
	*x = BulkImportResponse{}
	mi := &file_libs_proto_user_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkImportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkImportResponse) ProtoMessage() {}

func (x *BulkImportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_user_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkImportResponse.ProtoReflect.Descriptor instead.
func (*BulkImportResponse) Descriptor() ([]byte, []int) {
	return file_libs_proto_user_user_proto_rawDescGZIP(), []int{8}
}

func (x *BulkImportResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BulkImportResponse) GetFailureCount() int32 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *BulkImportResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ValidateCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCredentialsRequest) Reset() {
	*x = ValidateCredentialsRequest{}
	mi := &file_libs_proto_user_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCredentialsRequest) ProtoMessage() {}

func (x *ValidateCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_user_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCredentialsRequest.ProtoReflect.Descriptor instead.
func (*ValidateCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_libs_proto_user_user_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateCredentialsRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ValidateCredentialsRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ValidateCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	User          *UserResponse          `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"` // Reuse UserResponse or define minimal user info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCredentialsResponse) Reset() {
	*x = ValidateCredentialsResponse{}
	mi := &file_libs_proto_user_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCredentialsResponse) ProtoMessage() {}

func (x *ValidateCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_user_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCredentialsResponse.ProtoReflect.Descriptor instead.
func (*ValidateCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_libs_proto_user_user_proto_rawDescGZIP(), []int{10}
}

func (x *ValidateCredentialsResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateCredentialsResponse) GetUser() *UserResponse {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdatePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordRequest) Reset() {
	*x = UpdatePasswordRequest{}
	mi := &file_libs_proto_user_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordRequest) ProtoMessage() {}

func (x *UpdatePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_user_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return file_libs_proto_user_user_proto_rawDescGZIP(), []int{11}
}

func (x *UpdatePasswordRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type UpdatePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordResponse) Reset() {
	*x = UpdatePasswordResponse{}
	mi := &file_libs_proto_user_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordResponse) ProtoMessage() {}

func (x *UpdatePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_user_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordResponse.ProtoReflect.Descriptor instead.
func (*UpdatePasswordResponse) Descriptor() ([]byte, []int) {
	return file_libs_proto_user_user_proto_rawDescGZIP(), []int{12}
}

func (x *UpdatePasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_libs_proto_user_user_proto protoreflect.FileDescriptor

const file_libs_proto_user_user_proto_rawDesc = "" +
	"\n" +
	"\x1alibs/proto/user/user.proto\x12\x04user\"\xc5\x01\n" +
	"\vUserProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12!\n" +
	"\finstitute_id\x18\x05 \x01(\tR\vinstituteId\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\a \x01(\tR\tavatarUrl\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x8a\x01\n" +
	"\x14UpdateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\"[\n" +
	"\tInstitute\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\"y\n" +
	"\x16CreateInstituteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x1f\n" +
	"\vadmin_email\x18\x04 \x01(\tR\n" +
	"adminEmail\"\xdd\x01\n" +
	"\x11CreateUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12!\n" +
	"\finstitute_id\x18\x04 \x01(\tR\vinstituteId\x12+\n" +
	"\x11enrollment_number\x18\x05 \x01(\tR\x10enrollmentNumber\x12&\n" +
	"\x0especialization\x18\x06 \x01(\tR\x0especialization\"b\n" +
	"\fUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12#\n" +
	"\rtemp_password\x18\x03 \x01(\tR\ftempPassword\"Q\n" +
	"\x11BulkImportRequest\x12!\n" +
	"\finstitute_id\x18\x01 \x01(\tR\vinstituteId\x12\x19\n" +
	"\bcsv_data\x18\x02 \x01(\fR\acsvData\"v\n" +
	"\x12BulkImportResponse\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x05R\fsuccessCount\x12#\n" +
	"\rfailure_count\x18\x02 \x01(\x05R\ffailureCount\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\"N\n" +
	"\x1aValidateCredentialsRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"[\n" +
	"\x1bValidateCredentialsResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12&\n" +
	"\x04user\x18\x02 \x01(\v2\x12.user.UserResponseR\x04user\"S\n" +
	"\x15UpdatePasswordRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"2\n" +
	"\x16UpdatePasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xf7\x04\n" +
	"\vUserService\x128\n" +
	"\n" +
	"GetProfile\x12\x17.user.GetProfileRequest\x1a\x11.user.UserProfile\x12>\n" +
	"\rUpdateProfile\x12\x1a.user.UpdateProfileRequest\x1a\x11.user.UserProfile\x12@\n" +
	"\x0fCreateInstitute\x12\x1c.user.CreateInstituteRequest\x1a\x0f.user.Institute\x12C\n" +
	"\x14CreateInstituteAdmin\x12\x17.user.CreateUserRequest\x1a\x12.user.UserResponse\x12?\n" +
	"\x10CreateInstructor\x12\x17.user.CreateUserRequest\x1a\x12.user.UserResponse\x12<\n" +
	"\rCreateStudent\x12\x17.user.CreateUserRequest\x1a\x12.user.UserResponse\x12?\n" +
	"\n" +
	"BulkImport\x12\x17.user.BulkImportRequest\x1a\x18.user.BulkImportResponse\x12Z\n" +
	"\x13ValidateCredentials\x12 .user.ValidateCredentialsRequest\x1a!.user.ValidateCredentialsResponse\x12K\n" +
	"\x0eUpdatePassword\x12\x1b.user.UpdatePasswordRequest\x1a\x1c.user.UpdatePasswordResponseB0Z.github.com/4yrg/gradeloop-core/libs/proto/userb\x06proto3"

var (
	file_libs_proto_user_user_proto_rawDescOnce sync.Once
	file_libs_proto_user_user_proto_rawDescData []byte
)

func file_libs_proto_user_user_proto_rawDescGZIP() []byte {
	file_libs_proto_user_user_proto_rawDescOnce.Do(func() {
		file_libs_proto_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_libs_proto_user_user_proto_rawDesc), len(file_libs_proto_user_user_proto_rawDesc)))
	})
	return file_libs_proto_user_user_proto_rawDescData
}

var file_libs_proto_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_libs_proto_user_user_proto_goTypes = []any{
	(*UserProfile)(nil),                 // 0: user.UserProfile
	(*GetProfileRequest)(nil),           // 1: user.GetProfileRequest
	(*UpdateProfileRequest)(nil),        // 2: user.UpdateProfileRequest
	(*Institute)(nil),                   // 3: user.Institute
	(*CreateInstituteRequest)(nil),      // 4: user.CreateInstituteRequest
	(*CreateUserRequest)(nil),           // 5: user.CreateUserRequest
	(*UserResponse)(nil),                // 6: user.UserResponse
	(*BulkImportRequest)(nil),           // 7: user.BulkImportRequest
	(*BulkImportResponse)(nil),          // 8: user.BulkImportResponse
	(*ValidateCredentialsRequest)(nil),  // 9: user.ValidateCredentialsRequest
	(*ValidateCredentialsResponse)(nil), // 10: user.ValidateCredentialsResponse
	(*UpdatePasswordRequest)(nil),       // 11: user.UpdatePasswordRequest
	(*UpdatePasswordResponse)(nil),      // 12: user.UpdatePasswordResponse
}
var file_libs_proto_user_user_proto_depIdxs = []int32{
	6,  // 0: user.ValidateCredentialsResponse.user:type_name -> user.UserResponse
	1,  // 1: user.UserService.GetProfile:input_type -> user.GetProfileRequest
	2,  // 2: user.UserService.UpdateProfile:input_type -> user.UpdateProfileRequest
	4,  // 3: user.UserService.CreateInstitute:input_type -> user.CreateInstituteRequest
	5,  // 4: user.UserService.CreateInstituteAdmin:input_type -> user.CreateUserRequest
	5,  // 5: user.UserService.CreateInstructor:input_type -> user.CreateUserRequest
	5,  // 6: user.UserService.CreateStudent:input_type -> user.CreateUserRequest
	7,  // 7: user.UserService.BulkImport:input_type -> user.BulkImportRequest
	9,  // 8: user.UserService.ValidateCredentials:input_type -> user.ValidateCredentialsRequest
	11, // 9: user.UserService.UpdatePassword:input_type -> user.UpdatePasswordRequest
	0,  // 10: user.UserService.GetProfile:output_type -> user.UserProfile
	0,  // 11: user.UserService.UpdateProfile:output_type -> user.UserProfile
	3,  // 12: user.UserService.CreateInstitute:output_type -> user.Institute
	6,  // 13: user.UserService.CreateInstituteAdmin:output_type -> user.UserResponse
	6,  // 14: user.UserService.CreateInstructor:output_type -> user.UserResponse
	6,  // 15: user.UserService.CreateStudent:output_type -> user.UserResponse
	8,  // 16: user.UserService.BulkImport:output_type -> user.BulkImportResponse
	10, // 17: user.UserService.ValidateCredentials:output_type -> user.ValidateCredentialsResponse
	12, // 18: user.UserService.UpdatePassword:output_type -> user.UpdatePasswordResponse
	10, // [10:19] is the sub-list for method output_type
	1,  // [1:10] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_libs_proto_user_user_proto_init() }
func file_libs_proto_user_user_proto_init() {
	if File_libs_proto_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_libs_proto_user_user_proto_rawDesc), len(file_libs_proto_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_libs_proto_user_user_proto_goTypes,
		DependencyIndexes: file_libs_proto_user_user_proto_depIdxs,
		MessageInfos:      file_libs_proto_user_user_proto_msgTypes,
	}.Build()
	File_libs_proto_user_user_proto = out.File
	file_libs_proto_user_user_proto_goTypes = nil
	file_libs_proto_user_user_proto_depIdxs = nil
}
