// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: libs/proto/session/session.proto

package session

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserRole      string                 `protobuf:"bytes,3,opt,name=user_role,json=userRole,proto3" json:"user_role,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"` // Only returned on creation/refresh
	UserAgent     string                 `protobuf:"bytes,5,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	ClientIp      string                 `protobuf:"bytes,6,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	IsRevoked     bool                   `protobuf:"varint,7,opt,name=is_revoked,json=isRevoked,proto3" json:"is_revoked,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_libs_proto_session_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_session_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_libs_proto_session_session_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Session) GetUserRole() string {
	if x != nil {
		return x.UserRole
	}
	return ""
}

func (x *Session) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *Session) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *Session) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *Session) GetIsRevoked() bool {
	if x != nil {
		return x.IsRevoked
	}
	return false
}

func (x *Session) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *Session) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserRole      string                 `protobuf:"bytes,2,opt,name=user_role,json=userRole,proto3" json:"user_role,omitempty"`
	UserAgent     string                 `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	ClientIp      string                 `protobuf:"bytes,4,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_libs_proto_session_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_session_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_libs_proto_session_session_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateSessionRequest) GetUserRole() string {
	if x != nil {
		return x.UserRole
	}
	return ""
}

func (x *CreateSessionRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *CreateSessionRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_libs_proto_session_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_session_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_libs_proto_session_session_proto_rawDescGZIP(), []int{2}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RefreshSessionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	OldRefreshToken string                 `protobuf:"bytes,2,opt,name=old_refresh_token,json=oldRefreshToken,proto3" json:"old_refresh_token,omitempty"` // For verification
	NewRefreshToken string                 `protobuf:"bytes,3,opt,name=new_refresh_token,json=newRefreshToken,proto3" json:"new_refresh_token,omitempty"` // To update the hash
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RefreshSessionRequest) Reset() {
	*x = RefreshSessionRequest{}
	mi := &file_libs_proto_session_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSessionRequest) ProtoMessage() {}

func (x *RefreshSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_session_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSessionRequest.ProtoReflect.Descriptor instead.
func (*RefreshSessionRequest) Descriptor() ([]byte, []int) {
	return file_libs_proto_session_session_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RefreshSessionRequest) GetOldRefreshToken() string {
	if x != nil {
		return x.OldRefreshToken
	}
	return ""
}

func (x *RefreshSessionRequest) GetNewRefreshToken() string {
	if x != nil {
		return x.NewRefreshToken
	}
	return ""
}

type RevokeSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionRequest) Reset() {
	*x = RevokeSessionRequest{}
	mi := &file_libs_proto_session_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionRequest) ProtoMessage() {}

func (x *RevokeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_session_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionRequest.ProtoReflect.Descriptor instead.
func (*RevokeSessionRequest) Descriptor() ([]byte, []int) {
	return file_libs_proto_session_session_proto_rawDescGZIP(), []int{4}
}

func (x *RevokeSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RevokeSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionResponse) Reset() {
	*x = RevokeSessionResponse{}
	mi := &file_libs_proto_session_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionResponse) ProtoMessage() {}

func (x *RevokeSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_session_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionResponse.ProtoReflect.Descriptor instead.
func (*RevokeSessionResponse) Descriptor() ([]byte, []int) {
	return file_libs_proto_session_session_proto_rawDescGZIP(), []int{5}
}

func (x *RevokeSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RevokeAllUserSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAllUserSessionsRequest) Reset() {
	*x = RevokeAllUserSessionsRequest{}
	mi := &file_libs_proto_session_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAllUserSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAllUserSessionsRequest) ProtoMessage() {}

func (x *RevokeAllUserSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_session_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAllUserSessionsRequest.ProtoReflect.Descriptor instead.
func (*RevokeAllUserSessionsRequest) Descriptor() ([]byte, []int) {
	return file_libs_proto_session_session_proto_rawDescGZIP(), []int{6}
}

func (x *RevokeAllUserSessionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RevokeAllUserSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RevokedCount  int32                  `protobuf:"varint,1,opt,name=revoked_count,json=revokedCount,proto3" json:"revoked_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAllUserSessionsResponse) Reset() {
	*x = RevokeAllUserSessionsResponse{}
	mi := &file_libs_proto_session_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAllUserSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAllUserSessionsResponse) ProtoMessage() {}

func (x *RevokeAllUserSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libs_proto_session_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAllUserSessionsResponse.ProtoReflect.Descriptor instead.
func (*RevokeAllUserSessionsResponse) Descriptor() ([]byte, []int) {
	return file_libs_proto_session_session_proto_rawDescGZIP(), []int{7}
}

func (x *RevokeAllUserSessionsResponse) GetRevokedCount() int32 {
	if x != nil {
		return x.RevokedCount
	}
	return 0
}

var File_libs_proto_session_session_proto protoreflect.FileDescriptor

const file_libs_proto_session_session_proto_rawDesc = "" +
	"\n" +
	" libs/proto/session/session.proto\x12\asession\"\x8d\x02\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_role\x18\x03 \x01(\tR\buserRole\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x05 \x01(\tR\tuserAgent\x12\x1b\n" +
	"\tclient_ip\x18\x06 \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"is_revoked\x18\a \x01(\bR\tisRevoked\x12\x1d\n" +
	"\n" +
	"expires_at\x18\b \x01(\x03R\texpiresAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\"\x88\x01\n" +
	"\x14CreateSessionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_role\x18\x02 \x01(\tR\buserRole\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgent\x12\x1b\n" +
	"\tclient_ip\x18\x04 \x01(\tR\bclientIp\"2\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x8e\x01\n" +
	"\x15RefreshSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12*\n" +
	"\x11old_refresh_token\x18\x02 \x01(\tR\x0foldRefreshToken\x12*\n" +
	"\x11new_refresh_token\x18\x03 \x01(\tR\x0fnewRefreshToken\"5\n" +
	"\x14RevokeSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"1\n" +
	"\x15RevokeSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"7\n" +
	"\x1cRevokeAllUserSessionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"D\n" +
	"\x1dRevokeAllUserSessionsResponse\x12#\n" +
	"\rrevoked_count\x18\x01 \x01(\x05R\frevokedCount2\x8a\x03\n" +
	"\x0eSessionService\x12@\n" +
	"\rCreateSession\x12\x1d.session.CreateSessionRequest\x1a\x10.session.Session\x12:\n" +
	"\n" +
	"GetSession\x12\x1a.session.GetSessionRequest\x1a\x10.session.Session\x12B\n" +
	"\x0eRefreshSession\x12\x1e.session.RefreshSessionRequest\x1a\x10.session.Session\x12N\n" +
	"\rRevokeSession\x12\x1d.session.RevokeSessionRequest\x1a\x1e.session.RevokeSessionResponse\x12f\n" +
	"\x15RevokeAllUserSessions\x12%.session.RevokeAllUserSessionsRequest\x1a&.session.RevokeAllUserSessionsResponseB3Z1github.com/4yrg/gradeloop-core/libs/proto/sessionb\x06proto3"

var (
	file_libs_proto_session_session_proto_rawDescOnce sync.Once
	file_libs_proto_session_session_proto_rawDescData []byte
)

func file_libs_proto_session_session_proto_rawDescGZIP() []byte {
	file_libs_proto_session_session_proto_rawDescOnce.Do(func() {
		file_libs_proto_session_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_libs_proto_session_session_proto_rawDesc), len(file_libs_proto_session_session_proto_rawDesc)))
	})
	return file_libs_proto_session_session_proto_rawDescData
}

var file_libs_proto_session_session_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_libs_proto_session_session_proto_goTypes = []any{
	(*Session)(nil),                       // 0: session.Session
	(*CreateSessionRequest)(nil),          // 1: session.CreateSessionRequest
	(*GetSessionRequest)(nil),             // 2: session.GetSessionRequest
	(*RefreshSessionRequest)(nil),         // 3: session.RefreshSessionRequest
	(*RevokeSessionRequest)(nil),          // 4: session.RevokeSessionRequest
	(*RevokeSessionResponse)(nil),         // 5: session.RevokeSessionResponse
	(*RevokeAllUserSessionsRequest)(nil),  // 6: session.RevokeAllUserSessionsRequest
	(*RevokeAllUserSessionsResponse)(nil), // 7: session.RevokeAllUserSessionsResponse
}
var file_libs_proto_session_session_proto_depIdxs = []int32{
	1, // 0: session.SessionService.CreateSession:input_type -> session.CreateSessionRequest
	2, // 1: session.SessionService.GetSession:input_type -> session.GetSessionRequest
	3, // 2: session.SessionService.RefreshSession:input_type -> session.RefreshSessionRequest
	4, // 3: session.SessionService.RevokeSession:input_type -> session.RevokeSessionRequest
	6, // 4: session.SessionService.RevokeAllUserSessions:input_type -> session.RevokeAllUserSessionsRequest
	0, // 5: session.SessionService.CreateSession:output_type -> session.Session
	0, // 6: session.SessionService.GetSession:output_type -> session.Session
	0, // 7: session.SessionService.RefreshSession:output_type -> session.Session
	5, // 8: session.SessionService.RevokeSession:output_type -> session.RevokeSessionResponse
	7, // 9: session.SessionService.RevokeAllUserSessions:output_type -> session.RevokeAllUserSessionsResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_libs_proto_session_session_proto_init() }
func file_libs_proto_session_session_proto_init() {
	if File_libs_proto_session_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_libs_proto_session_session_proto_rawDesc), len(file_libs_proto_session_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_libs_proto_session_session_proto_goTypes,
		DependencyIndexes: file_libs_proto_session_session_proto_depIdxs,
		MessageInfos:      file_libs_proto_session_session_proto_msgTypes,
	}.Build()
	File_libs_proto_session_session_proto = out.File
	file_libs_proto_session_session_proto_goTypes = nil
	file_libs_proto_session_session_proto_depIdxs = nil
}
