'use client';

import {
    ShieldCheck,
    Save,
    Cpu,
    GitBranch,
    Flag,
    Settings2,
    Eye
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue
} from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Slider } from "@/components/ui/slider";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";

export default function IntegrityPage() {
    return (
        <div className="flex flex-col gap-6 max-w-5xl mx-auto">
            <div className="flex items-center justify-between">
                <div>
                    <h2 className="text-2xl font-bold tracking-tight">Integrity & AI Detection</h2>
                    <p className="text-muted-foreground">Rules and signals for academic integrity.</p>
                </div>
                <Button>
                    <Save className="mr-2 h-4 w-4" />
                    Save Settings
                </Button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <Card>
                    <CardHeader>
                        <CardTitle className="flex items-center gap-2">
                            <Cpu className="h-5 w-5" />
                            AI Gen Likelihood Model
                        </CardTitle>
                        <CardDescription>Configure the detection model for AI-generated code.</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-6">
                        <div className="flex items-center justify-between">
                            <div className="space-y-0.5">
                                <Label className="text-base">Enable AI Detection</Label>
                                <p className="text-sm text-muted-foreground">
                                    Flag submissions likely generated by LLMs.
                                </p>
                            </div>
                            <Switch defaultChecked />
                        </div>
                        <div className="space-y-4 pt-4 border-t">
                            <div className="flex justify-between">
                                <Label>Confidence Threshold</Label>
                                <Badge variant="secondary">80%</Badge>
                            </div>
                            <Slider defaultValue={[80]} max={100} step={1} />
                            <p className="text-[10px] text-muted-foreground italic">
                                Higher thresholds reduce false positives but may miss subtle AI usage.
                            </p>
                        </div>
                    </CardContent>
                </Card>

                <Card>
                    <CardHeader>
                        <CardTitle className="flex items-center gap-2">
                            <GitBranch className="h-5 w-5" />
                            Code Lineage Tracking
                        </CardTitle>
                        <CardDescription>Track the evolution of student code over time.</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-6">
                        <div className="flex items-center justify-between">
                            <div className="space-y-0.5">
                                <Label className="text-base">GitHub Sync</Label>
                                <p className="text-sm text-muted-foreground">
                                    Connect student repos for commit history analysis.
                                </p>
                            </div>
                            <Switch />
                        </div>
                        <div className="flex items-center justify-between">
                            <div className="space-y-0.5">
                                <Label className="text-base">IDE Telemetry</Label>
                                <p className="text-sm text-muted-foreground">
                                    Analyze development patterns and paste events.
                                </p>
                            </div>
                            <Switch defaultChecked />
                        </div>
                        <div className="space-y-2 pt-2 border-t text-sm">
                            <Label>Source weighting (IDE vs Commits)</Label>
                            <div className="flex items-center gap-4">
                                <span className="text-xs">IDE</span>
                                <Slider defaultValue={[70]} max={100} step={1} className="flex-1" />
                                <span className="text-xs">GIT</span>
                            </div>
                        </div>
                    </CardContent>
                </Card>

                <Card className="md:col-span-2">
                    <CardHeader>
                        <CardTitle className="flex items-center gap-2">
                            <Flag className="h-5 w-5" />
                            Auto-Flag Rules
                        </CardTitle>
                        <CardDescription>Define criteria for automatic "Integrity Flag" generation.</CardDescription>
                    </CardHeader>
                    <CardContent>
                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                            {[
                                { title: "Abnormal Paste Behavior", desc: "Large blocks of code pasted in short intervals." },
                                { title: "High External Similarity", desc: "Significant matches with online resources/past years." },
                                { title: "Viva-Code Disconnect", desc: "Viva performance significantly lower than code quality." },
                                { title: "Rapid Iteration", desc: "Successful submission after very few attempts." },
                                { title: "Shared IP Detection", desc: "Submissions from multiple students on same IP." },
                            ].map((rule) => (
                                <div key={rule.title} className="flex items-start gap-3 p-4 rounded-lg border bg-muted/20">
                                    <Checkbox id={rule.title} defaultChecked />
                                    <div className="space-y-1">
                                        <Label htmlFor={rule.title} className="text-sm font-semibold cursor-pointer leading-none">
                                            {rule.title}
                                        </Label>
                                        <p className="text-xs text-muted-foreground leading-relaxed">
                                            {rule.desc}
                                        </p>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </CardContent>
                </Card>
            </div>
        </div>
    );
}
